#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — a failing command inside a pipeline is otherwise silent.
#   - `sha256sum` for lockfile hashing — never hand-rolled (universal coreutils).
#   - Backoff 1s / 2s / 4s (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — always writable inside the sandbox.
#   - Exec target is `npm start`, which the project declares as its single-command
#     boot: prestart builds the Vite client to dist/client, then the tsx server
#     runs migrate -> schema self-check -> seed-if-empty -> queue-non-empty assert
#     -> listen 0.0.0.0:3000. We deliberately do NOT use the `dev` script
#     (`tsx watch`): its file watcher hits inotify limits on the constrained
#     sandbox and the app never serves. The build already produces dist/client
#     via prestart, so a watcher-free production start is both correct and stable.
#   - SQLite is file-based (./data), migrated and seeded by the server on boot;
#     there is no compose file and no host DB CLI to invoke here.

set -euo pipefail

# === Bash version guard ===
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Single-instance guard ===
exec 200>/tmp/pivota-dev.lock
if ! flock -n 200; then
  echo "[pivota] start-dev.sh already running (lock held) — exiting; poll the ready port instead" >&2
  exit 0
fi

# === Already-up fast path (#219) ===
READY_PORTS="3000"
DEV_STATE="/tmp/pivota-dev-boot-state"
dev_boot_state() {
  printf '%s|%s' \
    "$(git rev-parse HEAD 2>/dev/null || echo no-git)" \
    "$(docker compose config 2>/dev/null | sha256sum 2>/dev/null | cut -d' ' -f1)"
}
dev_ports_answering() {
  local p ok=1
  [ -n "${READY_PORTS// /}" ] || return 1
  for p in $READY_PORTS; do
    if (exec 3<>"/dev/tcp/127.0.0.1/$p") 2>/dev/null; then exec 3>&-; ok=0; fi
  done
  return $ok
}
if [[ "${PIVOTA_DEV_FORCE_RESTART:-}" != "1" ]] \
   && [[ -f "$DEV_STATE" ]] \
   && [[ "$(cat "$DEV_STATE" 2>/dev/null)" == "$(dev_boot_state)" ]] \
   && dev_ports_answering; then
  echo "[pivota] dev stack already up on port(s) ${READY_PORTS} with unchanged HEAD — skipping restart (set PIVOTA_DEV_FORCE_RESTART=1 to override)"
  exit 0
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding ===
# The server binds 0.0.0.0:3000 by default (config.CARGODEMO_HOST || '0.0.0.0');
# set explicitly so the preview iframe can reach it regardless of any inherited env.
export CARGODEMO_HOST="0.0.0.0"
export CARGODEMO_PORT="3000"
export HOST="0.0.0.0"
export PORT="3000"

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] seeding .env from .env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
      continue
    fi
    if [[ "$line" != *\"* && "$line" != *\'* ]]; then
      line="$(printf '%s' "$line" | sed -E 's/[[:space:]]+#.*$//')"
    fi
    value="${line#*=}"
    value_lc="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ "$value_lc" == change_me* || "$value_lc" == changeme* ]]; then
      generated="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
      printf '%s=%s\n' "$key" "${generated:0:48}"
      echo "[pivota] generated random value for placeholder $key" >&2
    else
      printf '%s\n' "$line"
    fi
  done < .env.example > .env
fi

# === D-11.6 (#510): load .env into THIS process's environment ===
if [[ -f .env ]]; then
  echo "[pivota] loading .env into the environment"
  PIVOTA_ENV_KEEP="$(mktemp)"
  while IFS= read -r _pivota_key; do
    if [[ -n "${!_pivota_key+x}" ]]; then
      declare -p "$_pivota_key" 2>/dev/null || true
    fi
  done < <(sed -nE 's/^[[:space:]]*(export[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)=.*/\2/p' .env | sort -u) \
       > "$PIVOTA_ENV_KEEP"
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
  # shellcheck disable=SC1090
  . "$PIVOTA_ENV_KEEP"
  rm -f "$PIVOTA_ENV_KEEP"
  unset PIVOTA_ENV_KEEP _pivota_key
fi

# === D-11.7 (#510): workspace-hoisted binaries on PATH ===
export PATH="$PWD/node_modules/.bin:$PATH"

# === D-12: idempotent install via lockfile hash + presence check ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="package-lock.json"
INSTALL_PRESENCE_CHECK="node_modules"
INSTALL_CMD='npm ci --include=dev'

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  local rc=0
  bash -c "$INSTALL_CMD" || rc=$?
  if (( rc == 0 )); then
    return 0
  fi
  echo "[pivota] WARN 'npm ci' failed (exit=$rc) — falling back to 'npm install --include=dev'"
  local rc2=0
  npm install --include=dev || rc2=$?
  if (( rc2 == 0 )); then
    return 0
  fi
  echo "[pivota] FATAL install failed (exit=$rc2) — dev server cannot start; resolve the dependency issue in the manifest" >&2
  return "$rc2"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")
  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi
  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
# `npm start` is the single boot command: prestart builds dist/client, then the
# tsx server migrates the SQLite schema, runs its blocking self-check, seeds when
# empty, asserts the queue is non-empty, and binds 0.0.0.0:3000.
EXEC_CMD='npm start'

dev_boot_state > "$DEV_STATE" 2>/dev/null || true

ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
